# Properties file for Shortener service
# This file will only be active when profile 'shortener' is active

# Spring properties
spring:
  application:
    name: shortener-service

  # Spring Datasource JDBC
  datasource:
    platform: hsqldb
    url: jdbc:hsqldb:mem:.
    username: sa
    password:
    driverClassName: org.hsqldb.jdbcDriver

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

# HTTP Server
server:
  port: 8082
