# Spring properties
spring:
  # Spring Datasource JDBC
  datasource:
    platform: hsqldb
    url: jdbc:hsqldb:mem:.
    username: sa
    password:
    driverClassName: org.hsqldb.jdbcDriver

  # View Resolver
  view:
    prefix: resources/static
    suffix: html
